### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Timerunning** [shangjingbo1226/ChineseWordCloud#1]
{
	"resource": "/D:/Chrome下载/ChineseWordCloud-master/create_word_cloud.py",
	"owner": "python",
	"code": "E0001",
	"severity": 8,
	"message": "E0001:invalid syntax (<string>, line 31)",
	"source": "pylint",
	"startLineNumber": 31,
	"startColumn": 1,
	"endLineNumber": 31,
	"endColumn": 1
}

**Comment by shangjingbo1226** [comment]
Are you using Python 3? Please change the print from Python 2 to Python 3.
